var DATABASE_URL="localhost:3000";
var PRIVATE_DATABASE_USER="username";
var PRIVATE_DATABASE_PASSWORD="password";
var PRIVATE_DATABASE_NAME="databasename";

exports.DATABASE_URL = DATABASE_URL;
exports.PRIVATE_DATABASE_USER = PRIVATE_DATABASE_USER;
exports.PRIVATE_DATABASE_PASSWORD = PRIVATE_DATABASE_PASSWORD;
exports.PRIVATE_DATABASE_NAME = PRIVATE_DATABASE_NAME;